import Link from "next/link";
import { PageHero } from "@/components/page-elements";
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata({ title: "Privacy Policy", description: "Learn how information is handled when you visit the ALVITEQ website, use the enquiry form, or contact the company.", path: "/privacy" });

export default function PrivacyPage() {
  return <><PageHero eyebrow="Legal" title="Privacy Policy" intro="This policy explains the limited information involved when you visit the ALVITEQ website or contact us." />
    <article className="legal container"><p className="legal-date">Effective 13 August 2026</p><h2>1. Scope</h2><p>This policy applies to the public website at alviteq.com, the website enquiry service, and direct correspondence about ALVITEQ. Use of the OwnKeep app is covered by the separate <Link href="/products/ownkeep/privacy">OwnKeep Privacy Policy</Link>.</p><h2>2. Website delivery and analytics</h2><p>Cloudflare may process technical request information such as IP address, browser details, timestamps, requested pages, performance measurements, and security signals to deliver, protect, and operate the website. Cloudflare Web Analytics may provide aggregate, cookie-free page, device, browser, and Core Web Vitals information. ALVITEQ does not use this analytics data to identify contact-form users or record form contents.</p><h2>3. Information you provide</h2><p>The enquiry form can collect topic, product interest, name, email, organisation, country, role, subject, message, and privacy acknowledgement. Direct email may also include information and attachments you choose to send. We use this information to respond, manage the relationship, prevent abuse, and maintain necessary business records.</p><h2>4. Verification and abuse prevention</h2><p>Cloudflare Turnstile processes technical signals to verify form submissions. Short-lived pseudonymous source hashes and idempotency records may be used for rate limiting and duplicate prevention. Turnstile tokens and raw request headers are not stored with enquiries.</p><h2>5. Sensitive information</h2><p>Do not submit patient names, medical records, clinical information, passwords, credentials, recovery material, identity documents, or private OwnKeep records. ALVITEQ does not need those items to answer normal enquiries.</p><h2>6. Storage and retention</h2><p>Accepted enquiries may be stored in Cloudflare D1 for up to 90 days while unanswered. Information needed for an established business relationship may be retained longer where reasonably necessary. Expired rate-limit and duplicate-prevention records are scheduled for deletion. Aggregate conversion counters do not contain message contents or contact identities.</p><h2>7. Sharing</h2><p>Information may be processed by service providers used for website delivery, security, storage, and business communication, or disclosed when legally required. ALVITEQ does not sell enquiry information or correlate it with anonymous browsing analytics.</p><h2>8. Your choices</h2><p>You may ask about personal information submitted through the enquiry service or direct correspondence, subject to applicable legal limitations. Contact <a href="mailto:privacy@alviteq.com">privacy@alviteq.com</a>.</p><h2>9. Changes</h2><p>Material updates will be published on this page with a revised effective date.</p></article>
  </>;
}
